#!/bin/sh

$HOME/applications/itksnap/itksnap-3.8.0-20190612-Linux-gcc64/bin/itksnap &

# font="Hack Bold 16"
# # Launch ITKSnap
# version=$(printf "itksnap 3.8.0\nitksnap 4.4.0" | wmenu -f "$font" -c -l 2 -p "Version ")
#
# case $version in
#   "itksnap 3.8.0")
#     $HOME/applications/itksnap/itksnap-3.8.0-20190612-Debian10-gcc64/bin/itksnap &
#     ;;
#   "itksnap 4.4.0")
#     $HOME/applications/itksnap/itksnap-4.4.0-20250909-Linux-x86_64/bin/itksnap &
#     ;;
#   *)
#     exit 0
#     ;;
# esac

