#!/bin/sh

MAX_SNAPSHOTS=10

count_snapshots() {
  sudo timeshift --list-snapshots | sed '1,/^------/d' | sed '/^$/d' | wc -l
}

delete_all_snapshots() {
  echo "sudo timeshift --delete-all"
}

create_snapshot() {
  COMMENT="$1"
  if [ -z "$COMMENT" ]; then
    echo "sudo timeshift --create"
  else
    echo "sudo timeshift --create --comments $COMMENT"
  fi
}

check_snapshots() {
  if [ "$(count_snapshots)" -gt "$MAX_SNAPSHOTS" ]; then
    notify-send -t 3000 "Snapshots" "Deleting all snapshots\nand creating new base snapshot"
    delete_all_snapshots
    echo "create with argument:"
    create_snapshot "base snapshot"
  else
    echo "less than max snaps, creating new snapshot"
    create_snapshot
  fi
}

check_snapshots
